### ISSUE TITLE
Address panic in multireader iterator

### ISSUE THREAD

**Issue by robskillington** [m3db/m3db#144]
```
panic: runtime error: index out of range

goroutine 2815650 [running]:
panic(0xa76940, 0xc42000e0e0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding/m3tsz.(*readerIterator).Current(0xd2d51e8180, 0xecf9e1f01, 0x0, 0xeefe60, 0x28b4576c1162192c, 0x413c01, 0x0, 0x0, 0x0)
        /var/cache/udeploy/r/statsdex_m3dbnode/sjc1-produ-0000000283-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding/m3tsz/iterator.go:355 +0x139
code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding.(*multiReaderIterator).moveIteratorToValidNext(0xc9c3fb73b0, 0x7f010f41b378, 0xd2d51e8180, 0x7f010f41b378)
        /var/cache/udeploy/r/statsdex_m3dbnode/sjc1-produ-0000000283-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding/multi_reader_iterator.go:167 +0x8e
code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding.(*multiReaderIterator).moveIteratorsToNext(0xc9c3fb73b0)
        /var/cache/udeploy/r/statsdex_m3dbnode/sjc1-produ-0000000283-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding/multi_reader_iterator.go:146 +0x10d
code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding.(*multiReaderIterator).moveToNext(0xc9c3fb73b0)
        /var/cache/udeploy/r/statsdex_m3dbnode/sjc1-produ-0000000283-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding/multi_reader_iterator.go:95 +0x309
code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding.(*multiReaderIterator).Next(0xc9c3fb73b0, 0xecf9e1ffb)
        /var/cache/udeploy/r/statsdex_m3dbnode/sjc1-produ-0000000283-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/encoding/multi_reader_iterator.go:67 +0xa9
code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/client.(*blocksResult).mergeReaders(0xc597a55e60, 0xecf9df480, 0xc500000000, 0xeefe60, 0xc43bc842a0, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
        /var/cache/udeploy/r/statsdex_m3dbnode/sjc1-produ-0000000283-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/client/session.go:1851 +0x174
code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/client.(*blocksResult).addBlockFromPeer(0xc597a55e60, 0xec70c0, 0xc536a033c0, 0xd0a6c55680, 0x0, 0x0)
        /var/cache/udeploy/r/statsdex_m3dbnode/sjc1-produ-0000000283-v2/tmp/src/code.uber.internal/infra/statsdex/vendor/github.com/m3db/m3db/client/session.go:1829 +0x81a
```

**Comment by robskillington** [comment]
Fixed by https://github.com/m3db/m3db/pull/154
